InhiblabCore/vue-hooks-plus

- packages/hooks/docs/.vitepress/config.ts
- packages/hooks/package.json
- packages/hooks/pnpm-lock.yaml
- packages/hooks/src/index.ts
- packages/hooks/src/useFetchs/demo/demo.vue
- packages/hooks/src/useFetchs/index.md
- packages/hooks/src/useFetchs/index.ts
- packages/hooks/src/useFocusWithin/index.ts
- packages/hooks/src/useRequest/docs/basic/demo/demo.vue
- packages/hooks/src/useRequest/docs/fetchs/index.md
- packages/hooks/src/useUpdate/demo/demo1.vue
- packages/hooks/src/useUpdate/index.md
- packages/hooks/src/useUrlState/demo/demo.vue
- packages/hooks/src/useUrlState/index.md
- packages/hooks/src/useUrlState/index.ts
- 新增 useUrlState 和  useFetch
- 优化文档config
- 调整个别函数引用路径
> feat: 新增 useUrlState 和  useFetch

- packages/hooks/docs/.vitepress/config.ts
- packages/hooks/package.json
- packages/hooks/src/index.ts
- packages/hooks/src/useFullscreen/demo/demo.vue
- packages/hooks/src/useFullscreen/demo/demo1.vue
- packages/hooks/src/useFullscreen/index.md
- packages/hooks/src/useFullscreen/index.ts
- packages/hooks/src/useKeyPress/index.md
> feat: use-fullscreen

- .github/COMMIT-zh-CN.md
- .github/workflows/node-ci.yml
- packages/hooks/scripts/config.ts
- packages/hooks/vite.config.ts
> chore: github tips

- packages/hooks/src/useBoolean/index.ts
- packages/hooks/src/useFormatResult/index.ts
- packages/hooks/src/useInterval/index.ts
- packages/hooks/src/useLockFn/index.ts
- packages/hooks/src/useUrlState/index.ts
> refactor: lint and code style

- .github/COMMIT.md
- commitlint.config.js
| 🇺🇸 English |   New English commit template        |
| 🇨🇳 Chinese |  新增英文 commit 模版          |
> style: update commitlint describe

- .gitignore
Reason: #24 
| 🇺🇸 English |  Code style optimization         |
| 🇨🇳 Chinese |  代码优化          |
> style: delete useless code

- .gitignore
| 🇺🇸 English |   add new annotation        |
| 🇨🇳 Chinese |  新增注释         |
> style: add new annotation (#27)

- .gitignore
- commitlint.config.js
| 🇺🇸 English |   optimized  commit-lint code        |
| 🇨🇳 Chinese |    优化commit-lint代码       |
> style: optimized code

- README.zh-CN.md
- packages/hooks/docs/.vitepress/config.ts
- packages/hooks/src/createUseStorageState/index.ts
- packages/hooks/src/useExternal/index.ts
- packages/hooks/src/useFavicon/index.ts
- packages/hooks/src/usePreview/index.ts
- packages/hooks/src/useRequest/plugins/useAutoRunPlugin.ts
- packages/hooks/src/useRequest/plugins/useDebouncePlugin.ts
- packages/hooks/src/useRequest/plugins/useLoadingDelayPlugin.ts
- packages/hooks/src/useRequest/plugins/usePollingPlugin.ts
- packages/hooks/src/useRequest/plugins/useRefreshOnWindowFocusPlugin.ts
- packages/hooks/src/useRequest/useRequestImplement.ts
- packages/hooks/src/useTimeout/index.ts
Reference solution: #23 
| 🇺🇸 English |   syntactic sugar 🍬 unref  replace isRef         |
| 🇨🇳 Chinese |   语法糖unref 代替 isRef  优化代码风格       |
> refactor: syntactic sugar 🍬 unref  replace isRef 

- packages/hooks/docs/.vitepress/config.ts
- packages/hooks/src/index.ts
- packages/hooks/src/useSetState/demo/demo.vue
- packages/hooks/src/useSetState/index.md
- packages/hooks/src/useSetState/index.tsx
| 🇺🇸 English | add use-set-state  |
| 🇨🇳 Chinese |  添加 use-set-state  |
> feat: add use-set-state

- packages/hooks/scripts/build.ts
- packages/hooks/src/useAsyncOrder/__tests__/index.spec.ts
- packages/hooks/src/useDebounce/__tests__/index.spec.ts
- packages/hooks/src/useDebounceFn/__tests__/index.spec.ts
- packages/hooks/src/useDrag/__tests__/index.spec.ts
- packages/hooks/src/useEventListener/__tests__/index.spec.ts
- packages/hooks/src/useFavicon/__tests__/index.spec.ts
- packages/hooks/src/useFavicon/demo/demo.vue
- packages/hooks/src/useFetchs/__tests__/index.spec.ts
- packages/hooks/src/useFetchs/demo/demo.vue
- packages/hooks/src/useLockFn/__tests__/index.spec.ts
- packages/hooks/src/useRequest/__tests__/debounce.spec.ts
- packages/hooks/src/useRequest/__tests__/delay.spec.ts
- packages/hooks/src/useRequest/__tests__/plugin.spec.ts
- packages/hooks/src/useRequest/__tests__/polling.spec.ts
- packages/hooks/src/useRequest/__tests__/ready.spec.ts
- packages/hooks/src/useRequest/__tests__/refreshDeps.spec.ts
- packages/hooks/src/useRequest/__tests__/retry.spec.ts
- packages/hooks/src/useRequest/__tests__/throttle.spec.ts
- packages/hooks/src/useThrottle/__tests__/index.spec.ts
- packages/hooks/src/useUpdate/__tests__/index.spec.ts
- packages/hooks/test-utils/renderHook.ts
- packages/hooks/test-utils/sleep.ts
- packages/hooks/tsconfig.json
- packages/hooks/vitest.config.ts
⚠️ use vue composition API warn
| 🇺🇸 English |   add & apply render-hook test   composition API   |
| 🇨🇳 Chinese |    添加和应用 render-hook 测试组合式API      |
> test: add render-hook 

- packages/hooks/docs/.vitepress/config.ts
- packages/hooks/src/index.ts
- packages/hooks/src/useWebSocket/demo/demo.vue
- packages/hooks/src/useWebSocket/index.md
- packages/hooks/src/useWebSocket/index.ts
| 🇺🇸 English |    add use-web-socket       |
| 🇨🇳 Chinese |   添加 use-web-socket        |
> feat: use-web-socket

- .gitignore
- package.json
- packages/hooks/package.json
- packages/hooks/scripts/build.ts
- packages/hooks/src/useRequest/__tests__/polling.spec.ts
- pnpm-lock.yaml
reason: #49 
| 🇺🇸 English |    fix type for build       |
| 🇨🇳 Chinese |     修复构建时候检查类型出错      |
> fix: type for build

- packages/hooks/docs/.vitepress/config.ts
- packages/hooks/src/useRequest/useRequest.ts
Reason: #57 
| 🇺🇸 English |  fix  use-request type      |
| 🇨🇳 Chinese |  修复 use-request 类型         |
> fix: use-request type

- packages/hooks/src/useRequest/__tests__/plugin.spec.ts
- packages/hooks/src/useRequest/types.ts
Reason: #57  data & error type
| 🇺🇸 English |     fix use-request data & error type      |
| 🇨🇳 Chinese |    修复 use-request data & error 类型       |
> fix: use-request data & error type

- package.json
- packages/hooks/docs/.vitepress/config.ts
- packages/hooks/package.json
- packages/hooks/src/useRequest/docs/pluginDoc/demo/demo.vue
- packages/hooks/src/useRequest/types.ts
- pnpm-lock.yaml
- tsconfig.json
-  Internationalization cannot be converted on the current page
-  mobile annot use internationalization [bug]
-  use @vue-hooks-plus/vitepress@1.1.8
| 🇺🇸 English |     optimized locale  & support the current page      |
| 🇨🇳 Chinese |      优化国际化 & 支持当前页面转换     |
> docs: optimized locale  & support the current page

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE-zh-CN.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
| 🇺🇸 English |      creating issue template    |
| 🇨🇳 Chinese |      创建问题模版     |
> chore: creating issue

- LICENSE
- README.md
- README.zh-CN.md
- commitlint.config.js
- packages/hooks/README.md
| 🇺🇸 English |    refactor repo core information      |
| 🇨🇳 Chinese |   重构仓库核心信息x        |
> refactor: core information

- packages/hooks/docs/.vitepress/components/button/button.vue
- packages/hooks/docs/.vitepress/theme/var.less
- packages/hooks/src/useRequest/docs/basic/demo/demo1.vue
- packages/hooks/src/useRequest/docs/basic/demo/demo2.vue
- packages/hooks/src/useRequest/docs/basic/demo/demo3.vue
- packages/hooks/src/useRequest/docs/basic/demo/demo5.vue
- packages/hooks/src/useRequest/docs/basic/demo/demo6.vue
- packages/hooks/src/useRequest/docs/basic/demo/demo7.vue
| 🇺🇸 English |    optimized demo style input & button       |
| 🇨🇳 Chinese |   优化示例样式 input & button       |
> docs: optimized demo style input & button

- packages/hooks/src/useRequest/types.ts
Reason: #71 
| 🇺🇸 English |    fix use-request option debounceMaxWait type       |
| 🇨🇳 Chinese |    修复 use-request 配置项 debounceMaxWait 的类型x    |
> fix: use-request option debounceMaxWait type

- DEV_DOCUMENT.md
- README.md
- README.zh-CN.md
- packages/hooks/README.md
- packages/hooks/docs/.vitepress/config.ts
| 🇺🇸 English |  change playground site         |
| 🇨🇳 Chinese |    改变演练场跳转网站
> docs: change playground site

- README.md
- README.zh-CN.md
- packages/hooks/README.md
| 🇺🇸 English |    readme optimize       |
| 🇨🇳 Chinese |    readme 优化       |
> style: readme optimize

- packages/hooks/docs/.vitepress/theme/home/Badge.vue
- packages/hooks/docs/guide/index.en-US.md
- packages/hooks/docs/guide/index.zh-CN.md
| 🇺🇸 English |    auto-import-vite guide       |
| 🇨🇳 Chinese |    auto-import-vite指南       |
> docs: auto-import-vite guide

- README.md
- README.zh-CN.md
- packages/hooks/README.md
| 🇺🇸 English |     readme      |
| 🇨🇳 Chinese |     readme      |
> style: readme

- packages/resolvers/package.json
- packages/resolvers/src/index.ts
- packages/resolvers/src/unplugin-auto-import/index.ts
| 🇺🇸 English |     resolvers@1.1.1       |
| 🇨🇳 Chinese |     resolvers@1.1.1       |
> feat: resolvers@1.1.1

- .github/workflows/ci.yml
- DEV_DOCUMENT.md
- package.json
- packages/hooks/package.json
- packages/hooks/scripts/plugin.ts
- packages/hooks/scripts/utils.ts
- packages/hooks/src/useRequest/Fetch.ts
- packages/hooks/src/useRequest/docs/basic/index.en-US.md
- packages/hooks/src/useRequest/docs/basic/index.zh-CN.md
- packages/hooks/src/useRequest/plugins/useAutoRunPlugin.ts
- packages/hooks/src/useRequest/plugins/useCachePlugin.ts
- packages/hooks/src/useRequest/plugins/useDebouncePlugin.ts
- packages/hooks/src/useRequest/plugins/useLoadingDelayPlugin.ts
- packages/hooks/src/useRequest/plugins/usePollingPlugin.ts
- packages/hooks/src/useRequest/plugins/useRefreshOnWindowFocusPlugin.ts
- packages/hooks/src/useRequest/plugins/useRetryPlugin.ts
- packages/hooks/src/useRequest/plugins/useThrottlePlugin.ts
- packages/hooks/src/useRequest/types.ts
- packages/hooks/src/useRequest/useRequest.ts
- packages/resolvers/package.json
- pnpm-lock.yaml
- scripts/bootstrap.ts
- scripts/build.ts
- scripts/docs.ts
- scripts/gitPage.ts
- scripts/utilts.ts
| 🇺🇸 English |   run type & use-request type optimized        |
| 🇨🇳 Chinese |  根目录运行方式和use-request 类型优化        |
> chore: run type & use-request type optimized

- packages/hooks/package.json
- packages/hooks/src/useRequest/Fetch.ts
- packages/hooks/src/useRequest/docs/basic/demo/demo.vue
- packages/hooks/src/useRequest/docs/basic/index.en-US.md
- packages/hooks/src/useRequest/docs/basic/index.zh-CN.md
- packages/hooks/src/useRequest/plugins/useAutoRunPlugin.ts
- packages/hooks/src/useRequest/types.ts
- packages/hooks/src/useRequest/useRequestImplement.ts
| 🇺🇸 English |   use-request option new feature initialData        |
| 🇨🇳 Chinese |   use-request 配置新特性 initialData        |
> feat: ✨ use-request option new feature initialData

- packages/hooks/package.json
- packages/hooks/src/useRequest/docs/refreshDeps/demo/demo.vue
- packages/hooks/src/useRequest/plugins/useAutoRunPlugin.ts
| 🇺🇸 English |   use-request ready as parameter, dependent refresh does not update         |
| 🇨🇳 Chinese |   use-request ready 作为参数，依赖刷新失效
> fix: 🔧 use-request ready as parameter, dependent refresh does not update 

- CONTRIBUTING.md
- README.md
- README.zh-CN.md
- packages/hooks/README.md
| 🇺🇸 English |    readme example entry       |
| 🇨🇳 Chinese |    readme 例子入口       |
> style: example entry

- packages/hooks/src/useRequest/Fetch.ts
`setUpdatadata` rename `setUpdateData`
> types: fix typo

- packages/hooks/src/useRequest/docs/basic/index.en-US.md
- packages/hooks/src/useRequest/docs/basic/index.zh-CN.md
- packages/hooks/src/useRequest/docs/refreshDeps/index.en-US.md
- packages/hooks/src/useRequest/docs/refreshDeps/index.zh-CN.md
- packages/hooks/src/useRequest/types.ts
| 🇺🇸 English |    useRequest add notes       |
| 🇨🇳 Chinese |     useRequest  添加注释    |
> style: useRequest add notes

- packages/hooks/src/useAsyncOrder/__tests__/index.spec.ts
- packages/hooks/src/useAsyncOrder/demo/demo.vue
- packages/hooks/src/useAsyncOrder/index.en-US.md
- packages/hooks/src/useAsyncOrder/index.ts
- packages/hooks/src/useAsyncOrder/index.zh-CN.md
- packages/hooks/src/useBoolean/index.ts
- packages/hooks/src/useRequest/plugins/useCachePlugin.ts
| 🇺🇸 English |     add notes      |
| 🇨🇳 Chinese |     添加注释      |
> style: add notes

- packages/hooks/src/useRequest/docs/basic/index.en-US.md
- packages/hooks/src/useRequest/docs/basic/index.zh-CN.md
| 🇺🇸 English |  docs fix context        |
| 🇨🇳 Chinese |     文档修复上下文      |
> docs: fix context

- package.json
- packages/hooks/docs/.vitepress/theme/home/Home.vue
- packages/hooks/docs/.vitepress/theme/home/index.less
- packages/hooks/docs/.vitepress/theme/var.less
- packages/hooks/docs/guide/index.en-US.md
- packages/hooks/docs/guide/index.zh-CN.md
- pnpm-lock.yaml
| 🇺🇸 English |   optimized Theme        |
| 🇨🇳 Chinese |   优化主题       |
> docs: optimized Theme

- packages/hooks/src/useRequest/Fetch.ts
- packages/hooks/src/useRequest/__tests__/refreshDeps-auto.spec.ts
- packages/hooks/src/useRequest/__tests__/refreshDeps.spec.ts
- packages/hooks/src/useRequest/docs/global/index.en-US.md
- packages/hooks/src/useRequest/docs/global/index.zh-CN.md
- packages/hooks/src/useRequest/docs/loadingDelay/demo/demo.vue
- packages/hooks/src/useRequest/docs/pluginDoc/demo/demo.vue
- packages/hooks/src/useRequest/docs/pluginDoc/index.en-US.md
- packages/hooks/src/useRequest/docs/pluginDoc/index.zh-CN.md
- packages/hooks/src/useRequest/docs/refreshOnWindowFocus/index.en-US.md
- packages/hooks/src/useRequest/docs/refreshOnWindowFocus/index.zh-CN.md
- packages/hooks/src/useRequest/plugins/useDebouncePlugin.ts
- packages/hooks/src/useRequest/plugins/useThrottlePlugin.ts
- packages/hooks/src/useRequest/useRequestImplement.ts
- packages/hooks/src/useRequest/utils/subscribeFocus.ts
| 🇺🇸 English |    use-request injection warning & optimized code       |
| 🇨🇳 Chinese |    修复use-request injection warning & 代码优化
> fix: use-request injection warning & optimized code

- package.json
- packages/hooks/src/useRequest/Fetch.ts
- packages/hooks/src/useRequest/docs/cache/demo/demo4.vue
- packages/hooks/src/useRequest/docs/global/demo/demo.vue
- packages/hooks/src/useRequest/docs/refreshDeps/demo/demo1.vue
- packages/hooks/src/useRequest/plugins/usePollingPlugin.ts
- packages/hooks/src/useRequest/useRequestImplement.ts
- packages/hooks/src/useWebSocket/demo/demo.vue
- packages/hooks/src/useWebSocket/index.ts
- packages/hooks/vite.config.ts
- packages/types/index.d.ts
- packages/types/tsconfig.json
- packages/types/vite.config.ts
- pnpm-lock.yaml
| 🇺🇸 English | fix   use-request auto deps refresh plugins invalid        |
| 🇨🇳 Chinese |   修复  use-request 自动依赖收集插件失效         |
> fix: use-request auto deps refresh plugins invalid

- packages/hooks/package.json
- packages/hooks/src/useRequest/useRequestImplement.ts
- packages/use-request/package.json
- packages/use-request/src/useRequestImplement.ts
| 🇺🇸 English |     delete log      |
| 🇨🇳 Chinese |    delete 日志      |
> style: delete log

- packages/hooks/src/useRequest/docs/plugins/broadcastChannel/index.en-US.md
- packages/hooks/src/useRequest/docs/refreshDeps/index.en-US.md
- packages/hooks/src/useRequest/docs/refreshDeps/index.zh-CN.md
| 🇺🇸 English |  optimized docs context         |
| 🇨🇳 Chinese |  优化文档上下文         |
> docs: optimized docs context

- packages/hooks/docs/.vitepress/theme/home/HomeTeam.vue
- packages/hooks/docs/.vitepress/theme/home/TeamMember.vue
- packages/hooks/docs/contributors.ts
- packages/hooks/src/useAsyncOrder/demo/demo.vue
- packages/hooks/src/useAsyncOrder/index.ts
- packages/hooks/src/useEventEmitter/event.ts
- packages/hooks/src/useKeyPress/index.ts
- packages/hooks/src/useRequest/plugins/useDebouncePlugin.ts
- packages/use-worker/vite.config.ts
| 🇺🇸 English |    ` lodash` bundle size optimization.       |
| 🇨🇳 Chinese |    `lodash` 包体积优化       |
> perf:  lodash bundle size optimization.

- .github/auto-comment.yml
- .github/release-drafter.yml
- package.json
- packages/use-immer/package.json
- pnpm-lock.yaml
| 🇺🇸 English |   update  deps and test socket       |
| 🇨🇳 Chinese |  更新依赖，测试socket        |
> chore: update  deps

- packages/hooks/src/useRequest/docs/refreshDeps/demo/demo1.vue
- packages/hooks/src/useRequest/plugins/useAutoRunPlugin.ts
- packages/hooks/src/useRequest/useRequestImplement.ts
| 🇺🇸 English |    fix use-request auto collect deps first request twice and ignore mount       |
| 🇨🇳 Chinese |     修复自动依赖收集首次进行两次请求并且忽略mount时的请求      |
> fix: use-request auto collect deps first request twice and ignore mount

- packages/hooks/src/useUrlState/index.ts
| 🇺🇸 English | fix error in url state modification caused by an immutable variable         |
| 🇨🇳 Chinese |  修复不可变变量导致的修改URL状态错误         |
> fix: error in url state modification caused by an immutable variable

- packages/hooks/docs/.vitepress/router.ts
- packages/hooks/src/index.ts
- packages/hooks/src/useLongPress/__tests__/index.spec.ts
- packages/hooks/src/useLongPress/demo/demo.vue
- packages/hooks/src/useLongPress/index.en-US.md
- packages/hooks/src/useLongPress/index.ts
- packages/hooks/src/useLongPress/index.zh-CN.md
- packages/hooks/src/utils/domTarget.ts
| Language     | Changelog          |
|--------------|--------------------|
| 🇺🇸 English | add use-long-press |
| 🇨🇳 Chinese | 添加 use-long-press  |
> feat: add use-long-press

- packages/hooks/src/useRequest/devtools/devtools.ts
- packages/hooks/src/useRequest/devtools/store.ts
- packages/hooks/src/useRequest/docs/debounce/demo/demo.vue
- packages/hooks/src/useRequest/docs/devtools/index.en-US.md
- packages/hooks/src/useRequest/docs/devtools/index.zh-CN.md
- packages/hooks/src/useRequest/docs/pluginDoc/demo/demo.vue
- packages/hooks/src/useRequest/plugins/useAutoRunPlugin.ts
- packages/hooks/src/useRequest/plugins/useCachePlugin.ts
- packages/hooks/src/useRequest/plugins/useDebouncePlugin.ts
- packages/hooks/src/useRequest/plugins/useDevtoolsPlugin.ts
- packages/hooks/src/useRequest/plugins/useLoadingDelayPlugin.ts
- packages/hooks/src/useRequest/plugins/usePollingPlugin.ts
- packages/hooks/src/useRequest/plugins/useRefreshOnWindowFocusPlugin.ts
- packages/hooks/src/useRequest/plugins/useRetryPlugin.ts
- packages/hooks/src/useRequest/plugins/useThrottlePlugin.ts
- packages/hooks/src/useRequest/types.ts
- packages/types/index.d.ts
- packages/types/package.json
- packages/use-request-plugins/package.json
- packages/use-request-plugins/src/useBroadcastChannelPlugin/useBroadcastChannel.ts
- packages/use-request-plugins/src/useFetchingPlugin/store.ts
- packages/use-request-plugins/src/useFetchingPlugin/useFetching.ts
| 🇺🇸 English |    useRequest devtools@v2       |
| 🇨🇳 Chinese |    useRequest devtools@v2       |
> feat: useRequest devtools@v2

- packages/hooks/src/useRequest/Fetch.ts
- packages/hooks/src/useRequest/__tests__/basic.spec.ts
- packages/hooks/src/useRequest/docs/basic/demo/demo5.vue
- packages/hooks/src/useRequest/docs/basic/index.en-US.md
- packages/hooks/src/useRequest/docs/basic/index.zh-CN.md
| 🇺🇸 English | use-request support rollbackError |
| 🇨🇳 Chinese | use-request 支持错误回滚 |
> feat: use-request support rollbackError

- packages/hooks/docs/.vitepress/router.ts
- packages/hooks/src/index.ts
- packages/hooks/src/useElementBounding/__tests__/index.spec.ts
- packages/hooks/src/useElementBounding/demo/demo.vue
- packages/hooks/src/useElementBounding/index.en-US.md
- packages/hooks/src/useElementBounding/index.ts
- packages/hooks/src/useElementBounding/index.zh-CN.md
- packages/hooks/src/useResizeObserver/__tests__/index.spec.ts
- packages/hooks/src/useResizeObserver/demo/demo.vue
- packages/hooks/src/useResizeObserver/index.en-US.md
- packages/hooks/src/useResizeObserver/index.ts
- packages/hooks/src/useResizeObserver/index.zh-CN.md
> feat: Add useElementBounding and useResizeObserver

- .github/workflows/ci.yml
- packages/hooks/docs/.vitepress/router.ts
- packages/hooks/src/index.ts
- packages/hooks/src/useMutationObserver/__tests__/index.spec.ts
- packages/hooks/src/useMutationObserver/demo/demo.vue
- packages/hooks/src/useMutationObserver/index.en-US.md
- packages/hooks/src/useMutationObserver/index.ts
- packages/hooks/src/useMutationObserver/index.zh-CN.md
- packages/hooks/src/useRequest/__tests__/ready.spec.ts
| 🇺🇸 English |    useMutationObserver       |
| 🇨🇳 Chinese |    useMutationObserver       |
> feat: useMutationObserver

- packages/hooks/package.json
> chore: unpkg path

- packages/hooks/src/useResizeObserver/index.ts
对于 `hooks` 包新增体积分析插件配置，现在会在执行 `build` 命令操作时，自动生成构建体积分析文件 `visualizer.html`。
| 🇨🇳 Chinese |     ☑️      |
> feat: 优化useResizeObserver，避免在非浏览器环境下isSupported不能正确检测；避免没意义的deep监听

- packages/hooks/package.json
- packages/hooks/src/useResizeObserver/index.ts
> perf: isSupport above deps watch

- packages/hooks/docs/.vitepress/components/button/button.vue
- packages/hooks/docs/global.d.ts
- packages/hooks/tsconfig.json
- packages/vitepress/vitepress-demo-block/package.json
- packages/vitepress/vitepress-demo-block/src/Demo.vue
- packages/vitepress/vitepress-demo-block/src/SfcPlayground.vue
- packages/vitepress/vitepress-demo-block/src/useCopyCode.ts
> style: optimized something

- packages/vitepress/vitepress-demo-block/package.json
- packages/vitepress/vitepress-demo-block/src/SfcPlayground.vue
> docs: docs sfc play style

- packages/hooks/src/useFetchs/demo/demo.vue
- packages/hooks/src/useFetchs/index.ts
- packages/hooks/src/useInfiniteScroll/demo/demo.vue
- packages/hooks/src/useInfiniteScroll/demo/demo1.vue
- packages/hooks/src/useInfiniteScroll/demo/demo2.vue
- packages/hooks/src/useInfiniteScroll/demo/demo3.vue
- packages/hooks/src/useInfiniteScroll/demo/demo4.vue
> type: fix useFetch ref type

- packages/hooks/package.json
- packages/hooks/src/useRequest/useRequest.ts
- packages/use-request/package.json
- packages/use-request/src/useRequest.ts
> fix: use-request typing

- packages/hooks/src/useRequest/Fetch.ts
- packages/hooks/src/useRequest/docs/basic/demo/demo.vue
- packages/hooks/src/useRequest/types.ts
- packages/hooks/src/useRequest/useRequest.ts
- packages/hooks/src/useRequest/useRequestImplement.ts
- packages/use-request/src/Fetch.ts
- packages/use-request/src/types.ts
- packages/use-request/src/useRequest.ts
- packages/use-request/src/useRequestImplement.ts
> type: support initialData

- .vscode/setting.json
- packages/hooks/src/createUseStorageState/index.ts
- packages/hooks/src/useAsyncOrder/index.ts
- packages/hooks/src/useCounter/index.ts
- packages/hooks/src/useHover/index.ts
- packages/hooks/src/useInfiniteScroll/index.ts
- packages/hooks/src/useUrlState/index.ts
> perf: import way

- packages/hooks/src/useInfiniteScroll/index.ts
[[English Template / 英文模板](https://github.com/InhiblabCore/vue-hooks-plus/tree/master/.github/PULL_REQUEST_TEMPLATE.md)]
loading应表示是否正在进行首次请求，当前判断条件错误，造成首次执行时并没有正确变化
此为ahooks判断条件
| 语言    | 更新描述 |
| ------- | -------- |
| 🇺🇸 英文 |          |
| 🇨🇳 中文 |          |
⚠️ 请自检并全部**勾选全部选项**。⚠️
> fix: useInfiniteScroll中loading的错误表现

- .github/auto-comment.yml
- .github/auto_assign.yml
- .github/workflows/auto-assign.yml
- .github/workflows/greetings.yml
> feat: workflow

- docs/demo/request-formatResult/demo.vue
- docs/demo/request-polling/demo.vue
- docs/en/hooks/useRequest/plugin.md
- docs/tsconfig.json
- packages/hooks/package.json
- packages/hooks/src/useRequest/Fetch.ts
- packages/hooks/src/useRequest/types.ts
- pnpm-lock.yaml
> feat: use-request support format origin

- docs/demo/useMouse/demo.vue
- docs/demo/useMouse/demo1.vue
- docs/demo/useRequest/demo.vue
- packages/hooks/src/index.ts
- packages/hooks/src/useMouse/component.ts
- packages/hooks/src/useRequest/component-use/UseRequest.ts
> feat: support component
